version: 0.2
phases:
  install:
    commands:
      - pip install --user aws-sam-cli
      - sam package --template-file template.yml --s3-bucket layer-test-lamda --output-template-file package.yaml
artifacts:
  files:
    - '**/*'
